CREATE TABLE T_TGL_INTEGRAL_ORDER(
  ID CHAR(36) NOT NULL,
	ORDER_NO VARCHAR2(30) NOT NULL,
	PRODUCT_NO VARCHAR2(30) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	INTRODUCTION VARCHAR2(20),
	DETAILS VARCHAR2(120),
	INTEGRAL NUMBER(9) NOT NULL,
	CASH NUMBER(9,2) NOT NULL,
	CHANNEL VARCHAR2(60) NOT NULL,
	PLATFORM VARCHAR2(60) NOT NULL,
	STATUS VARCHAR2(20) NOT NULL,
	ONLINE_START_TIME DATE,
	ONLINE_END_TIME DATE,
	PARENT_ID CHAR(36),
	STOCK NUMBER(9),
	CREATE_TIME DATE,
	MOTIFY_TIME DATE,
	OPERATOR VARCHAR2(60),
  CONSTRAINT PK_TGL_INTEGRAL_ORDER PRIMARY KEY (ID)
);

COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.ID IS 'ID';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.CODE IS '渠道';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.NAME IS '名称';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.INTRODUCTION IS '简介';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.DETAILS IS '详情';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.INTEGRAL IS '消耗积分';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.CASH IS '消耗现金';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.CHANNEL IS '渠道';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.PLATFORM IS '平台';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.STATUS IS '状态';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.ONLINE_START_TIME IS '在线开始时间';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.ONLINE_END_TIME IS '在线结束时间';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.PARENT_ID IS '主商品ID';
COMMENT ON COLUMN T_TGL_INTEGRAL_ORDER.STOCK IS '库存';