CREATE TABLE T_TGL_INTEGRAL_ACCOUNT(
  ID CHAR(36) NOT NULL,
  ACCOUNT_NO NUMBER(18,0) NOT NULL,
  INTEGRAL NUMBER(10) default 0,
  AVAILABLE_INTEGRAL NUMBER(9,0) default 0,
  FREEZING_INTEGRAL NUMBER(9,0) default 0,
  CREATE_TIME DATE NOT NULL,
  MODIFY_TIME DATE NOT NULL,
  OPERATOR VARCHAR2(60),
  CONSTRAINT PK_TGL_INTEGRAL_ACCOUNT PRIMARY KEY(ID)
);