CREATE TABLE T_TGL_INTEGRAL_PRODUCT(
  ID CHAR(36) NOT NULL,
	CODE VARCHAR2(30) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	INTRODUCTION VARCHAR2(20),
	DETAILS VARCHAR2(120),
	INTEGRAL NUMBER(9) NOT NULL,
	CASH NUMBER(9,2) NOT NULL,
	CHANNEL VARCHAR2(60) NOT NULL,
	PLATFORM VARCHAR2(60) NOT NULL,
	STATUS VARCHAR2(20) NOT NULL,
	ONLINE_START_TIME DATE,
	ONLINE_END_TIME DATE,
	PARENT_ID CHAR(36),
	STOCK NUMBER(9),
	CREATE_TIME DATE,
	MOTIFY_TIME DATE,
	OPERATOR VARCHAR2(60),
  CONSTRAINT PK_TGL_INTEGRAL_PRODUCT PRIMARY KEY (ID)
);

COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.ID IS 'ID';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.CODE IS '渠道';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.NAME IS '名称';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.INTRODUCTION IS '简介';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.DETAILS IS '详情';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.INTEGRAL IS '消耗积分';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.CASH IS '消耗现金';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.CHANNEL IS '渠道';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.PLATFORM IS '平台';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.STATUS IS '状态';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.ONLINE_START_TIME IS '在线开始时间';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.ONLINE_END_TIME IS '在线结束时间';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.PARENT_ID IS '主商品ID';
COMMENT ON COLUMN T_TGL_INTEGRAL_PRODUCT.STOCK IS '库存';